--
-- Create new schema user
--

CREATE USER [SCHEMA NAME]
  IDENTIFIED BY "[PASSWORD]" 
  DEFAULT TABLESPACE  [TABLESPACE] 
  QUOTA 500M ON [TABLESPACE] ;

--allow user to login
GRANT CREATE SESSION TO [SCHEMA NAME] ;

-- SYSTEM PRIVILEGES
GRANT CREATE TABLE TO [SCHEMA NAME] ;
GRANT CREATE SEQUENCE TO [SCHEMA NAME] ;
GRANT CREATE TRIGGER TO [SCHEMA NAME] ;
GRANT CREATE SYNONYM TO [SCHEMA NAME] ;
GRANT CREATE VIEW TO [SCHEMA NAME] ;
GRANT CREATE MATERIALIZED VIEW TO [SCHEMA NAME] ;
GRANT ALTER SESSION TO [SCHEMA NAME] ;
GRANT CREATE DATABASE LINK TO [SCHEMA NAME];
GRANT CREATE PROCEDURE TO [SCHEMA NAME];
GRANT CREATE TYPE TO [SCHEMA NAME];
