--change password
ALTER User INSERUSERNAME IDENTIFIED BY INSERTNEWUSERPASSWORD;

-- GRANT PERMISSIONS
GRANT SELECT,INSERT,DELETE,UPDATE,CREATE SESSION ON TABLENAME TO USERNAME;
GRANT SELECT ON TABLENAME TO USERNAME;

